In [1]:
import pandas as pd

In [2]:
emp = {'name':['Nikhil','Amit','Rahul'],
        'gender':['Male','Male','Male'],
        'email':['nikhil@gmail.com','amit@yahoo.com','rahul@reddif.mail']}

In [3]:
# creating a dataframe

df_emp = pd.DataFrame(emp)

In [4]:
df_emp

     name gender              email
0  Nikhil   Male   nikhil@gmail.com
1    Amit   Male     amit@yahoo.com
2   Rahul   Male  rahul@reddif.mail

In [7]:
# apply function

df_emp['name'].apply(len)

0    6
1    4
2    5
Name: name, dtype: int64

In [8]:
# apply with user defined function

def update_email(email):
    return email.upper()

In [9]:
df_emp['email'].apply(update_email)

0     NIKHIL@GMAIL.COM
1       AMIT@YAHOO.COM
2    RAHUL@REDDIF.MAIL
Name: email, dtype: object

In [10]:
# applymap is for applying a similar function to entire dataframe

df_emp.applymap(len)

/var/folders/dw/248wnsc17x1d9lt__pxhm9080000gn/T/ipykernel_2394/317222757.py:3: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df_emp.applymap(len)

   name  gender  email
0     6       4     16
1     4       4     14
2     5       4     17

In [11]:
df_emp.applymap(update_email)

/var/folders/dw/248wnsc17x1d9lt__pxhm9080000gn/T/ipykernel_2394/2186760414.py:1: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df_emp.applymap(update_email)

     name gender              email
0  NIKHIL   MALE   NIKHIL@GMAIL.COM
1    AMIT   MALE     AMIT@YAHOO.COM
2   RAHUL   MALE  RAHUL@REDDIF.MAIL

In [15]:
df_emp['name'].str.upper()

0    NIKHIL
1      AMIT
2     RAHUL
Name: name, dtype: object

In [16]:
# applying string functions

df_emp['name'].str.lower()

0    nikhil
1      amit
2     rahul
Name: name, dtype: object

In [21]:
# contains function

df_emp['name'].str.startswith('A')

0    False
1     True
2    False
Name: name, dtype: bool

In [22]:
# Add new column

df_emp['Salary'] = 10000

In [23]:
df_emp

     name gender              email  Salary
0  Nikhil   Male   nikhil@gmail.com   10000
1    Amit   Male     amit@yahoo.com   10000
2   Rahul   Male  rahul@reddif.mail   10000

In [24]:
# new column with concatenate

df_emp['name_gender'] = df_emp['name']+' '+df_emp['gender']

In [25]:
df_emp

     name gender              email  Salary  name_gender
0  Nikhil   Male   nikhil@gmail.com   10000  Nikhil Male
1    Amit   Male     amit@yahoo.com   10000    Amit Male
2   Rahul   Male  rahul@reddif.mail   10000   Rahul Male

In [26]:
# delete rows

df_emp.drop(index=0) # dropping the rows which is at index 0

    name gender              email  Salary name_gender
1   Amit   Male     amit@yahoo.com   10000   Amit Male
2  Rahul   Male  rahul@reddif.mail   10000  Rahul Male

In [27]:
# filter

df_emp['Salary'] > 1000

0    True
1    True
2    True
Name: Salary, dtype: bool

In [28]:
# sort the dataframe

df_emp.sort_values(by='name') # by default it's in ascending

     name gender              email  Salary  name_gender
1    Amit   Male     amit@yahoo.com   10000    Amit Male
0  Nikhil   Male   nikhil@gmail.com   10000  Nikhil Male
2   Rahul   Male  rahul@reddif.mail   10000   Rahul Male

In [29]:
# sort the dataframe

df_emp.sort_values(by='name',ascending=False) # by descending

     name gender              email  Salary  name_gender
2   Rahul   Male  rahul@reddif.mail   10000   Rahul Male
0  Nikhil   Male   nikhil@gmail.com   10000  Nikhil Male
1    Amit   Male     amit@yahoo.com   10000    Amit Male

In [30]:
# to reset the index

df_emp.sort_index()

     name gender              email  Salary  name_gender
0  Nikhil   Male   nikhil@gmail.com   10000  Nikhil Male
1    Amit   Male     amit@yahoo.com   10000    Amit Male
2   Rahul   Male  rahul@reddif.mail   10000   Rahul Male

In [31]:
df_emp.sort_index(ascending=False)

     name gender              email  Salary  name_gender
2   Rahul   Male  rahul@reddif.mail   10000   Rahul Male
1    Amit   Male     amit@yahoo.com   10000    Amit Male
0  Nikhil   Male   nikhil@gmail.com   10000  Nikhil Male