### Pandas tutorial

In [2]:
import pandas as pd

In [3]:
emp = {'name':['Nikhil','Amit','Rahul'],
        'gender':['Male','Male','Male'],
        'email':['nikhil@gmail.com','amit@yahoo.com','rahul@reddif.mail']}

In [4]:
# creating a dataframe

df_emp = pd.DataFrame(emp)

In [5]:
df_emp

     name gender              email
0  Nikhil   Male   nikhil@gmail.com
1    Amit   Male     amit@yahoo.com
2   Rahul   Male  rahul@reddif.mail

In [6]:
# accessing name

df_emp['name']

0    Nikhil
1      Amit
2     Rahul
Name: name, dtype: object

In [7]:
df_emp.name

0    Nikhil
1      Amit
2     Rahul
Name: name, dtype: object

In [8]:
# info of df

df_emp.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    3 non-null      object
 1   gender  3 non-null      object
 2   email   3 non-null      object
dtypes: object(3)
memory usage: 204.0+ bytes

In [9]:
# describe

df_emp.describe()

          name gender             email
count        3      3                 3
unique       3      1                 3
top     Nikhil   Male  nikhil@gmail.com
freq         1      3                 1

In [10]:
type(df_emp['name'])

pandas.core.series.Series

In [11]:
# reading from files

df = pd.read_csv(r'/Users/nick_mac/Desktop/python/namastepython/orders.txt')

In [12]:
df.head()

,order_id,order_date,customer_name,city,category,product_id,sales,profit
0,CA-2018-100006,2018-09-07,Dennis Kane,New York City,Technology,TEC-PH-10002075,377.970,109.6113
1,CA-2018-100090,2018-07-08,Ed Braxton,San Francisco,Furniture,FUR-TA-10003715,502.488,-87.9354
2,CA-2018-100293,2018-03-14,Neil Französisch,Jacksonville,Office Supplies,OFF-PA-10000176,91.056,31.8696
3,CA-2018-100328,2018-01-28,Jasper Cacioppo,New York City,Office Supplies,OFF-BI-10000343,3.928,1.3257
4,CA-2018-100363,2018-04-08,Jim Mitchum,Glendale,Office Supplies,OFF-FA-10000611,2.368,0.8288

In [13]:
# top 10 rows

df.head(10)

,order_id,order_date,customer_name,city,category,product_id,sales,profit
0,CA-2018-100006,2018-09-07,Dennis Kane,New York City,Technology,TEC-PH-10002075,377.970,109.6113
1,CA-2018-100090,2018-07-08,Ed Braxton,San Francisco,Furniture,FUR-TA-10003715,502.488,-87.9354
2,CA-2018-100293,2018-03-14,Neil Französisch,Jacksonville,Office Supplies,OFF-PA-10000176,91.056,31.8696
3,CA-2018-100328,2018-01-28,Jasper Cacioppo,New York City,Office Supplies,OFF-BI-10000343,3.928,1.3257
4,CA-2018-100363,2018-04-08,Jim Mitchum,Glendale,Office Supplies,OFF-FA-10000611,2.368,0.8288
5,CA-2018-100391,2018-05-25,Barry Weirich,New York City,Office Supplies,OFF-PA-10001471,14.620,6.7252
6,CA-2018-100678,2018-04-18,Kunst Miller,Houston,Furniture,FUR-CH-10002602,317.058,-18.1176
7,CA-2018-100706,2018-12-16,Laurel Elliston,Springfield,Furniture,FUR-FU-10002268,29.460,9.7218
8,CA-2018-100762,2018-11-24,Nat Gilpin,Jackson,Office Supplies,OFF-AR-10000380,151.920,45.5760
9,CA-2018-100860,2018-03-26,Cindy Stewart,Pomona,Office Supplies,OFF-LA-10001982,18.750,9.0000

In [14]:
# bottom 10

df.tail(10)

,order_id,order_date,customer_name,city,category,product_id,sales,profit
4999,US-2021-167570,2021-12-08,Emily Grady,Philadelphia,Furniture,FUR-CH-10003396,215.544,-58.5048
5000,US-2021-167920,2021-12-09,John Lee,Richmond,Office Supplies,OFF-AP-10000159,214.900,62.3210
5001,US-2021-168116,2021-11-04,Grant Thornton,Burlington,Office Supplies,OFF-AP-10002457,167.440,14.6510
5002,US-2021-168613,2021-10-08,Gary McGarr,New York City,Furniture,FUR-CH-10002372,145.764,3.2392
5003,US-2021-168690,2021-01-07,Thais Sissman,Ormond Beach,Office Supplies,OFF-BI-10000145,2.808,-1.9656
5004,US-2021-168802,2021-11-03,Jack O'Briant,Seattle,Office Supplies,OFF-BI-10002393,18.368,5.9696
5005,US-2021-169320,2021-07-23,Lena Hernandez,Elkhart,Office Supplies,OFF-AR-10003602,11.680,5.4896
5006,US-2021-169488,2021-09-07,Allen Armold,Providence,Office Supplies,OFF-PA-10000157,39.960,18.7812
5007,US-2021-169502,2021-08-28,Matthew Grinstein,Milwaukee,Office Supplies,OFF-AP-10001947,91.600,26.5640
5008,US-2021-169551,2021-07-07,Rob Lucas,Philadelphia,Furniture,FUR-BO-10001519,87.210,-45.3492

In [15]:
# access single column

df['order_id']

0       CA-2018-100006
1       CA-2018-100090
2       CA-2018-100293
3       CA-2018-100328
4       CA-2018-100363
             ...
5004    US-2021-168802
5005    US-2021-169320
5006    US-2021-169488
5007    US-2021-169502
5008    US-2021-169551
Name: order_id, Length: 5009, dtype: object

In [16]:
# access multiple columns

df[['order_id','order_date','category']]

            order_id  order_date         category
0     CA-2018-100006  2018-09-07       Technology
1     CA-2018-100090  2018-07-08        Furniture
2     CA-2018-100293  2018-03-14  Office Supplies
3     CA-2018-100328  2018-01-28  Office Supplies
4     CA-2018-100363  2018-04-08  Office Supplies
...              ...         ...              ...
5004  US-2021-168802  2021-11-03  Office Supplies
5005  US-2021-169320  2021-07-23  Office Supplies
5006  US-2021-169488  2021-09-07  Office Supplies
5007  US-2021-169502  2021-08-28  Office Supplies
5008  US-2021-169551  2021-07-07        Furniture

[5009 rows x 3 columns]

In [17]:
# select row 1 using iloc which is called index loc

df.iloc[1]

order_id          CA-2018-100090
order_date            2018-07-08
customer_name         Ed Braxton
city               San Francisco
category               Furniture
product_id       FUR-TA-10003715
sales                    502.488
profit                  -87.9354
Name: 1, dtype: object

In [18]:
# row and column

df.iloc[0,2]

'Dennis Kane'

In [19]:
# loc is labeled based

df.loc[1]

order_id          CA-2018-100090
order_date            2018-07-08
customer_name         Ed Braxton
city               San Francisco
category               Furniture
product_id       FUR-TA-10003715
sales                    502.488
profit                  -87.9354
Name: 1, dtype: object

In [20]:
df.loc[1,'customer_name']

'Ed Braxton'

In [21]:
df.set_index('customer_name')

,order_id,order_date,city,category,product_id,sales,profit
customer_name,,,,,,,
Dennis Kane,CA-2018-100006,2018-09-07,New York City,Technology,TEC-PH-10002075,377.970,109.6113
Ed Braxton,CA-2018-100090,2018-07-08,San Francisco,Furniture,FUR-TA-10003715,502.488,-87.9354
Neil Französisch,CA-2018-100293,2018-03-14,Jacksonville,Office Supplies,OFF-PA-10000176,91.056,31.8696
Jasper Cacioppo,CA-2018-100328,2018-01-28,New York City,Office Supplies,OFF-BI-10000343,3.928,1.3257
Jim Mitchum,CA-2018-100363,2018-04-08,Glendale,Office Supplies,OFF-FA-10000611,2.368,0.8288
...,...,...,...,...,...,...,...
Jack O'Briant,US-2021-168802,2021-11-03,Seattle,Office Supplies,OFF-BI-10002393,18.368,5.9696
Lena Hernandez,US-2021-169320,2021-07-23,Elkhart,Office Supplies,OFF-AR-10003602,11.680,5.4896
Allen Armold,US-2021-169488,2021-09-07,Providence,Office Supplies,OFF-PA-10000157,39.960,18.7812
Matthew Grinstein,US-2021-169502,2021-08-28,Milwaukee,Office Supplies,OFF-AP-10001947,91.600,26.5640
Rob Lucas,US-2021-169551,2021-07-07,Philadelphia,Furniture,FUR-BO-10001519,87.210,-45.3492

In [22]:
# reset index

df.reset_index()

,index,order_id,order_date,customer_name,city,category,product_id,sales,profit
0,0,CA-2018-100006,2018-09-07,Dennis Kane,New York City,Technology,TEC-PH-10002075,377.970,109.6113
1,1,CA-2018-100090,2018-07-08,Ed Braxton,San Francisco,Furniture,FUR-TA-10003715,502.488,-87.9354
2,2,CA-2018-100293,2018-03-14,Neil Französisch,Jacksonville,Office Supplies,OFF-PA-10000176,91.056,31.8696
3,3,CA-2018-100328,2018-01-28,Jasper Cacioppo,New York City,Office Supplies,OFF-BI-10000343,3.928,1.3257
4,4,CA-2018-100363,2018-04-08,Jim Mitchum,Glendale,Office Supplies,OFF-FA-10000611,2.368,0.8288
...,...,...,...,...,...,...,...,...,...
5004,5004,US-2021-168802,2021-11-03,Jack O'Briant,Seattle,Office Supplies,OFF-BI-10002393,18.368,5.9696
5005,5005,US-2021-169320,2021-07-23,Lena Hernandez,Elkhart,Office Supplies,OFF-AR-10003602,11.680,5.4896
5006,5006,US-2021-169488,2021-09-07,Allen Armold,Providence,Office Supplies,OFF-PA-10000157,39.960,18.7812
5007,5007,US-2021-169502,2021-08-28,Matthew Grinstein,Milwaukee,Office Supplies,OFF-AP-10001947,91.600,26.5640
5008,5008,US-2021-169551,2021-07-07,Rob Lucas,Philadelphia,Furniture,FUR-BO-10001519,87.210,-45.3492

In [23]:
# iloc

df.iloc[1:5,1:3]

   order_date     customer_name
1  2018-07-08        Ed Braxton
2  2018-03-14  Neil Französisch
3  2018-01-28   Jasper Cacioppo
4  2018-04-08       Jim Mitchum

In [25]:
# loc

df.loc[1:5,['sales']]

     sales
1  502.488
2   91.056
3    3.928
4    2.368
5   14.620

In [26]:
# sort thr index

df.sort_index()

,order_id,order_date,customer_name,city,category,product_id,sales,profit
0,CA-2018-100006,2018-09-07,Dennis Kane,New York City,Technology,TEC-PH-10002075,377.970,109.6113
1,CA-2018-100090,2018-07-08,Ed Braxton,San Francisco,Furniture,FUR-TA-10003715,502.488,-87.9354
2,CA-2018-100293,2018-03-14,Neil Französisch,Jacksonville,Office Supplies,OFF-PA-10000176,91.056,31.8696
3,CA-2018-100328,2018-01-28,Jasper Cacioppo,New York City,Office Supplies,OFF-BI-10000343,3.928,1.3257
4,CA-2018-100363,2018-04-08,Jim Mitchum,Glendale,Office Supplies,OFF-FA-10000611,2.368,0.8288
...,...,...,...,...,...,...,...,...
5004,US-2021-168802,2021-11-03,Jack O'Briant,Seattle,Office Supplies,OFF-BI-10002393,18.368,5.9696
5005,US-2021-169320,2021-07-23,Lena Hernandez,Elkhart,Office Supplies,OFF-AR-10003602,11.680,5.4896
5006,US-2021-169488,2021-09-07,Allen Armold,Providence,Office Supplies,OFF-PA-10000157,39.960,18.7812
5007,US-2021-169502,2021-08-28,Matthew Grinstein,Milwaukee,Office Supplies,OFF-AP-10001947,91.600,26.5640
5008,US-2021-169551,2021-07-07,Rob Lucas,Philadelphia,Furniture,FUR-BO-10001519,87.210,-45.3492

In [28]:
# sort on name

df_1 = df.set_index(['customer_name'])

In [29]:
df_1.sort_index()

,order_id,order_date,city,category,product_id,sales,profit
customer_name,,,,,,,
Aaron Bergman,CA-2020-140935,2020-11-10,Oklahoma City,Furniture,FUR-BO-10003966,341.960,54.7136
Aaron Bergman,CA-2018-156587,2018-03-07,Seattle,Furniture,FUR-CH-10004477,48.712,5.4801
Aaron Bergman,CA-2018-152905,2018-02-18,Arlington,Office Supplies,OFF-ST-10000321,12.624,-2.5248
Aaron Hawkins,CA-2018-113768,2018-05-13,Los Angeles,Furniture,FUR-CH-10002439,279.456,20.9592
Aaron Hawkins,CA-2019-130113,2019-12-27,San Francisco,Office Supplies,OFF-ST-10000046,323.100,61.3890
...,...,...,...,...,...,...,...
Zuschuss Donatelli,CA-2018-143336,2018-08-27,San Francisco,Office Supplies,OFF-AR-10003056,8.560,2.4824
Zuschuss Donatelli,US-2020-147991,2020-05-05,Chattanooga,Furniture,FUR-FU-10004270,16.720,3.3440
Zuschuss Donatelli,CA-2021-141481,2021-06-11,Los Angeles,Office Supplies,OFF-AP-10004532,61.440,16.5888
Zuschuss Donatelli,CA-2020-152471,2020-07-08,Jacksonville,Office Supplies,OFF-PA-10004965,15.984,4.9950
Zuschuss Donatelli,CA-2020-167682,2020-04-03,Richmond,Furniture,FUR-FU-10003799,71.120,22.0472

In [ ]:
# see the category 

df['category'].unique()

array(['Technology', 'Furniture', 'Office Supplies'], dtype=object)

In [32]:
# category count

df['category'].value_counts()

category
Office Supplies    2773
Furniture          1764
Technology          472
Name: count, dtype: int64

In [37]:
# count on multiple columns

df[['category','city']].value_counts()

category         city
Office Supplies  New York City        257
                 Los Angeles          210
Furniture        New York City        157
Office Supplies  Philadelphia         152
                 San Francisco        149
Furniture        Los Angeles          138
Office Supplies  Seattle              109
                 Chicago               99
                 Houston               98
Furniture        San Francisco         91
                 Philadelphia          89
                 Seattle               84
                 Houston               68
Office Supplies  Columbus              61
Furniture        Chicago               56
Office Supplies  Dallas                47
                 Springfield           45
                 San Diego             43
Furniture        Columbus              40
Technology       Los Angeles           36
                 New York City         36
Furniture        San Diego             36
Office Supplies  Jacksonville          32
                 Detroit               27
                 Richmond              27
                 Newark                25
Technology       San Francisco         25
Furniture        Dallas                24
Technology       Philadelphia          24
Office Supplies  Miami                 23
Furniture        Springfield           23
Technology       Houston               22
Office Supplies  Jackson               21
Furniture        Detroit               21
Office Supplies  Long Beach            20
Furniture        Jacksonville          19
Technology       Seattle               19
Office Supplies  Phoenix               18
                 Rochester             18
                 Lancaster             18
                 Arlington             18
Furniture        Aurora                17
Office Supplies  Lakewood              17
                 Columbia              17
Technology       Chicago               16
Office Supplies  Fairfield             16
Furniture        Newark                15
Office Supplies  Lawrence              15
                 Aurora                15
Furniture        Columbia              14
Office Supplies  Charlotte             14
                 San Antonio           13
Furniture        Richmond              13
Office Supplies  Austin                13
Furniture        Louisville            13
Office Supplies  Atlanta               13
                 Nashville             12
                 Salem                 12
Furniture        Jackson               12
Office Supplies  Louisville            12
Furniture        Henderson             12
Office Supplies  Fayetteville          11
Furniture        Arlington             11
                 Milwaukee             11
                 Franklin              11
Office Supplies  Wilmington            11
                 Concord               11
                 Toledo                11
                 Roseville             10
                 Pasadena              10
Furniture        Lakewood              10
Office Supplies  San Jose              10
Technology       Columbus              10
Office Supplies  Cleveland             10
Furniture        San Jose              10
                 Concord               10
Office Supplies  Indianapolis          10
Furniture        Phoenix               10
Technology       Jacksonville          10
Furniture        San Antonio           10
Office Supplies  Riverside              9
                 Burlington             9
                 Quincy                 9
                 Glendale               9
                 Milwaukee              9
Furniture        Pasadena               9
Office Supplies  Baltimore              9
Furniture        Long Beach             9
Technology       San Diego              9
Furniture        Baltimore              9
Office Supplies  Lafayette              9
                 Cincinnati             9
                 Portland               9
Furniture        Rochester              9
Technology       Dallas                 9
Furniture        Oceanside              9
                 Fayetteville           8
                 Tucson                 8
                 Cleveland              8
Office Supplies  Huntsville             8
                 Minneapolis            8
Furniture        Fairfield              8
                 Tampa                  8
Office Supplies  Mesa                   8
Furniture        Miami                  8
Office Supplies  Plainfield             7
Furniture        Denver                 7
Office Supplies  Decatur                7
                 Virginia Beach         7
                 Franklin               7
Furniture        Lafayette              7
Office Supplies  Auburn                 7
Furniture        Huntsville             7
                 Lancaster              7
Office Supplies  Smyrna                 7
                 Memphis                7
                 Omaha                  7
                 Denver                 7
                 Hollywood              7
                 Henderson              7
                 Akron                  7
Furniture        Memphis                7
                 Oakland                7
Office Supplies  Florence               6
                 Las Vegas              6
                 Troy                   6
                 Fresno                 6
                 Tulsa                  6
                 Rockford               6
                 Grand Rapids           6
                 Providence             6
                 Chesapeake             6
Furniture        Troy                   6
                 Providence             6
                 Decatur                6
Office Supplies  Albuquerque            6
                 Fort Worth             6
Furniture        Marion                 6
Office Supplies  Roswell                6
Furniture        Charlotte              6
Office Supplies  Kent                   5
Furniture        Wilmington             5
                 Monroe                 5
Office Supplies  Fremont                5
                 Knoxville              5
                 Raleigh                5
                 Oklahoma City          5
                 Orange                 5
                 Santa Ana              5
Furniture        Minneapolis            5
Office Supplies  Little Rock            5
                 Hialeah                5
Furniture        Oklahoma City          5
Office Supplies  Greensboro             5
                 Salt Lake City         5
                 Middletown             5
                 Mount Vernon           5
Furniture        Tulsa                  5
Office Supplies  Bloomington            5
                 El Paso                5
Furniture        Buffalo                5
                 Fort Lauderdale        5
Technology       Newark                 5
Furniture        Dover                  5
Office Supplies  Bristol                5
Furniture        Fort Worth             5
Office Supplies  Des Moines             5
Technology       Springfield            5
Office Supplies  Carlsbad               5
                 Tampa                  5
                 Everett                5
Furniture        Clinton                5
Office Supplies  Asheville              5
                 Colorado Springs       5
Furniture        Knoxville              5
Technology       Detroit                5
Office Supplies  Newport News           4
                 Stockton               4
                 Durham                 4
Furniture        Costa Mesa             4
                 Colorado Springs       4
                 Peoria                 4
                 North Las Vegas        4
                 Paterson               4
Office Supplies  Oakland                4
                 Oceanside              4
                 Orlando                4
                 Morristown             4
                 Bowling Green          4
                 Peoria                 4
Technology       Charlotte              4
Furniture        El Paso                4
Office Supplies  Alexandria             4
Technology       Jackson                4
Office Supplies  Huntington Beach       4
Furniture        Raleigh                4
                 Burlington             4
                 Amarillo               4
                 Anaheim                4
                 Bakersfield            4
Technology       San Antonio            4
                 Raleigh                4
Office Supplies  Irving                 4
Technology       Omaha                  4
Furniture        Virginia Beach         4
Office Supplies  Lowell                 4
                 Chandler               4
Furniture        Watertown              4
Office Supplies  Moreno Valley          4
Furniture        Saint Petersburg       4
                 Saint Charles          4
Office Supplies  Carrollton             4
Furniture        Sacramento             4
Office Supplies  Meriden                4
Technology       Louisville             4
                 Long Beach             4
Office Supplies  Midland                4
Furniture        Chesapeake             4
Office Supplies  Monroe                 4
                 Clinton                4
                 Scottsdale             4
                 Bellevue               4
                 Waterbury              4
                 Redmond                4
Furniture        Glendale               4
                 Hialeah                4
                 Lawrence               4
                 Gilbert                4
Office Supplies  Anaheim                4
                 Tempe                  4
Furniture        Hampton                4
                 Grand Prairie          4
                 Lakeland               4
Office Supplies  Rancho Cucamonga       4
                 Sacramento             4
Furniture        Everett                4
                 Mesa                   4
                 Fresno                 4
Office Supplies  Bakersfield            4
                 Tallahassee            4
                 Pueblo                 4
                 Fort Lauderdale        4
Furniture        Montgomery             4
Office Supplies  Marion                 3
                 Apple Valley           3
Technology       Monroe                 3
                 Milwaukee              3
                 Miami                  3
                 Baltimore              3
Furniture        Harrisonburg           3
                 Salem                  3
Office Supplies  Waco                   3
                 Mcallen                3
                 San Bernardino         3
Furniture        Lorain                 3
Office Supplies  Watertown              3
Furniture        Roseville              3
                 Waynesboro             3
Office Supplies  Medford                3
Furniture        Santa Ana              3
                 Washington             3
Office Supplies  Freeport               3
                 Sterling Heights       3
                 Athens                 3
Furniture        Atlanta                3
                 Toledo                 3
                 Auburn                 3
Office Supplies  Johnson City           3
                 Lakeville              3
Furniture        Austin                 3
Office Supplies  Laredo                 3
Technology       Tallahassee            3
Furniture        Bloomington            3
Office Supplies  Manchester             3
                 Skokie                 3
Technology       Portland               3
Furniture        Vineland               3
Office Supplies  Tucson                 3
                 Cranston               3
                 Santa Clara            3
                 Loveland               3
                 Lubbock                3
Furniture        Chattanooga            3
Office Supplies  Santa Barbara          3
Furniture        Greensboro             3
Technology       Denver                 3
Office Supplies  Salinas                3
Furniture        Des Moines             3
                 Freeport               3
Office Supplies  Grand Prairie          3
                 Eagan                  3
Technology       Decatur                3
Furniture        Orem                   3
Office Supplies  Hempstead              3
Furniture        Omaha                  3
Office Supplies  Overland Park          3
                 Eau Claire             3
Technology       Cleveland              3
Office Supplies  Norwich                3
                 Redlands               3
Furniture        Fort Collins           3
                 Florence               3
Office Supplies  Perth Amboy            3
Furniture        Nashville              3
Office Supplies  Escondido              3
Furniture        Edmonds                3
Office Supplies  Plano                  3
Technology       Aurora                 3
                 Dover                  3
Furniture        La Porte               3
Office Supplies  Brentwood              3
Furniture        Plano                  3
                 Portland               3
Office Supplies  Murray                 3
                 Dover                  3
                 Wichita                3
                 New Rochelle           3
                 Saint Louis            3
                 Great Falls            3
Technology       Fort Lauderdale        3
Office Supplies  Woodstock              3
                 Frankfort              2
                 Fort Collins           2
                 Hoover                 2
                 Edinburg               2
                 Fargo                  2
                 Garland                2
                 Greenville             2
                 Delray Beach           2
                 Georgetown             2
                 Homestead              2
                 Gulfport               2
                 Haltom City            2
                 Independence           2
                 Hamilton               2
                 Inglewood              2
                 Coral Springs          2
                 Holland                2
                 Jonesboro              2
                 Dublin                 2
                 Cuyahoga Falls         2
                 Deltona                2
Furniture        Alexandria             2
Office Supplies  Garden City            2
Furniture        Akron                  2
Office Supplies  Laguna Niguel          2
Technology       Franklin               2
                 Evanston               2
                 Dublin                 2
                 Des Moines             2
                 Columbia               2
                 Cincinnati             2
                 Carrollton             2
                 Burlington             2
                 Brentwood              2
                 Bloomington            2
                 Austin                 2
                 Arlington              2
Office Supplies  Yuma                   2
                 Yonkers                2
                 Woonsocket             2
                 Woodbury               2
                 Wilson                 2
                 Wheeling               2
                 Westland               2
                 Westfield              2
                 West Palm Beach        2
                 Warwick                2
Technology       Florence               2
                 Greenville             2
Office Supplies  Urbandale              2
Technology       Huntsville             2
                 Yonkers                2
                 Wilmington             2
                 Warwick                2
                 Utica                  2
                 Tulsa                  2
                 Tucson                 2
                 Troy                   2
                 Plano                  2
                 Oakland                2
                 Norman                 2
                 New Bedford            2
                 Naperville             2
                 Modesto                2
                 Mesa                   2
                 Marion                 2
                 Lehi                   2
                 Lawrence               2
                 Lancaster              2
                 Lakewood               2
                 Kenosha                2
                 Jamestown              2
Office Supplies  Vallejo                2
                 Trenton                2
                 Las Cruces             2
                 Palm Coast             2
                 Orem                   2
                 Odessa                 2
                 North Miami            2
                 North Las Vegas        2
                 New Bedford            2
                 Naperville             2
                 Murfreesboro           2
                 Montgomery             2
                 Mobile                 2
                 Mission Viejo          2
                 Mesquite               2
                 Marysville             2
                 Marietta               2
                 Maple Grove            2
                 Madison                2
                 Macon                  2
                 Lorain                 2
                 Lodi                   2
                 Lewiston               2
                 Leominster             2
                 Lebanon                2
                 Owensboro              2
                 Parma                  2
                 Tigard                 2
                 Paterson               2
                 Thousand Oaks          2
                 Thomasville            2
                 The Colony             2
                 Tamarac                2
                 Suffolk                2
                 Spokane                2
                 Sparks                 2
                 Sioux Falls            2
                 Sandy Springs          2
                 Saint Petersburg       2
                 Saint Charles          2
                 Royal Oak              2
                 Revere                 2
                 Reno                   2
                 Redondo Beach          2
                 Reading                2
                 Provo                  2
                 Port Arthur            2
                 Pomona                 2
                 Pleasant Grove         2
                 Pembroke Pines         2
                 Port Saint Lucie       2
Technology       Yuma                   2
Furniture        Lakeville              2
                 Medina                 2
                 Olympia                2
                 Texas City             2
                 Chico                  2
                 Odessa                 2
                 Chester                2
                 Trenton                2
                 Chandler               2
                 Carrollton             2
                 Vancouver              2
                 Westfield              2
                 Westminster            2
                 Wheeling               2
                 Green Bay              2
                 Murfreesboro           2
                 Redmond                2
                 Mount Pleasant         2
                 Gresham                2
                 Brownsville            2
                 Broomfield             2
                 Bristol                2
                 Yonkers                2
                 Mobile                 2
                 Hackensack             2
                 Miramar                2
                 Middletown             2
                 Boynton Beach          2
Office Supplies  Amarillo               2
Furniture        Encinitas              2